# Generated by Django 3.1.7 on 2021-04-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrg',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
