# Generated by Django 3.1.7 on 2021-04-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0002_auto_20210404_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrg',
            name='age',
            field=models.IntegerField(max_length=120),
        ),
        migrations.CreateModel(
            name='NewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.IntegerField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Emp.userrg')),
            ],
        ),
    ]
