# Generated by Django 3.1.7 on 2021-04-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0003_auto_20210407_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userrg',
            name='age',
            field=models.IntegerField(),
        ),
    ]
