# Generated by Django 3.1.7 on 2021-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0004_auto_20210407_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='phoneno',
            field=models.IntegerField(default=9398753723),
        ),
    ]
