# Generated by Django 3.1.7 on 2021-04-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0005_auto_20210407_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrg',
            name='age',
            field=models.IntegerField(default=21),
        ),
    ]
